#@ load("@ytt:data", "data")
---
profile: full

ceip_policy_disclosed: true

buildservice:
  kp_default_repository: #@ "{}/{}/{}".format(data.values.container_registry.hostname, data.values.container_registry.project, data.values.container_registry.repository.build_service)
  kp_default_repository_username: #@ data.values.container_registry.username
  kp_default_repository_password: #@ data.values.container_registry.password
  tanzunet_username: #@ data.values.tanzunet.username
  tanzunet_password: #@ "{}".format(data.values.tanzunet.password)
  descriptor_name: "full"
  enable_automatic_dependency_updates: true

supply_chain: basic

cnrs:
  domain_name: #@ "cnrs.{}".format(data.values.domain)
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
  default_tls_secret: "tanzu-system-ingress/tap-cert"

ootb_supply_chain_basic:
  registry:
    server: #@ data.values.container_registry.hostname
    repository: #@ "{}/{}".format(data.values.container_registry.project, data.values.container_registry.repository.build_service)
  gitops:
    ssh_secret: ""

learningcenter:
  ingressDomain: #@ "tlc.{}".format(data.values.domain)
  ingressSecret:
    secretName: learningcenter-cert

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: #@ data.values.domain
  tls:
    secretName: tap-cert
    namespace: tanzu-system-ingress
  app_config:
    app:
      baseUrl: #@ "https://tap-gui.{}".format(data.values.domain)
    backend:
      baseUrl: #@ "https://tap-gui.{}".format(data.values.domain)
      cors:
        origin: #@ "https://tap-gui.{}".format(data.values.domain)

metadata_store:
  app_service_type: LoadBalancer

grype:
  namespace: "default"
  targetImagePullSecret: "tap-registry"

contour:
  envoy:
    service:
      type: LoadBalancer

accelerator:
  domain: #@ data.values.domain
  ingress:
    include: true
  tls:
    secretName: tap-cert
    namespace: tanzu-system-ingress
  server:
    service_type: ClusterIP
