#@data/values
---

#@overlay/match missing_ok=True
tanzunet:

container_registry:
  hostname: "gcr.io"
  project: "cso-pcfs-emea-mewald"
  repository:
    build_service: build-service
  #@overlay/match missing_ok=True
  username:
  #@overlay/match missing_ok=True
  password:
    
domain: tap.halusky.net